spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redakzia
    username: root
    password: 1986
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    platform: authorsdatabase
