spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redakzia
    username: root
    password: 1986
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    platform: authorsdatabase
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 25MB

file.upload-dir: .\\tables


user.exclepath: tables\\authors.xlsx
user.csvpath: tables\\authors.csv
